let r=Document.getElementById("heading1");
let b=Document.getElementsByTagName("h1");
let f=Document.getElementsByClassName("c1");
console.log(r);
console.log(b);
console.log(b[0]);
console.log(b[1]);
console.log(f);
console.log(r.innerText);
console.log(r.innerHTML);
console.log(r.textContent);